### ISSUE TITLE
HTMLFormatter does not work when set in a json file.

### ISSUE THREAD

**Issue by galli-leo** [sashgorokhov/python-telegram-handler#17]
I setup my config like this:
```
with open("logging.json", "r") as fd:
        logging.config.dictConfig(json.load(fd))
```

My logging.json file looks like this:

```

{
    "version": 1,
    "handlers": {
        "telegram": {
            "class": "telegram_handler.TelegramHandler",
            "formatter" : "telegram",
            "token": "xxx",
            "chat_id": "xxx"
        },
        "console":{
            "level": "DEBUG",
            "formatter" : "simple",
            "class": "logging.StreamHandler",
            "stream" : "ext://sys.stdout"
        },
        "file_handler": {
            "level": "INFO",
            "class": "logging.handlers.WatchedFileHandler",
            "formatter" : "simple",
            "filename": "downloader.log",
            "mode": "a",
            "encoding": "utf-8"
        }
    },
    "formatters": {
        "telegram": {
            "class": "telegram_handler.HtmlFormatter",
            "parse_mode" : "HTML",
            "format": "<code>%(asctime)s</code> <b>%(levelname)s</b>\nFrom %(name)s:%(funcName)s\n%(message)s"
        },
        "simple": {
            "class": "logging.Formatter",
            "format": "%(asctime)s | [%(levelname)s] %(name)15s %(lineno)4d: %(message)s"
        }
    },
    "loggers": {
        "my_logger": {
            "handlers": ["telegram"],
            "level": "INFO"
        }
    },
    "root": {
        "handlers": ["telegram", "console", "file_handler"],
        "level": "WARNING"
    }
}

```

If I do not set the `formatter` for the Telegram handler, a message with exception info won't have the exception info formatted at all. If I do set the formatter, the message in telegram is sent as plaintext (i.e. I see the html tags). Seems like the parse_mode might not be set when instantiated from the config file?

Screenshot:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/5339762/51071010-e52f8b00-164a-11e9-9af8-fdbae064472d.png">

**Comment by sashgorokhov** [comment]
Can you please try to remove the `"parse_mode" : "HTML"` param of `telegram` formatter from logging config? I bet that this param is passed down to logging.Formatter initializer which does not support it, so logging just silently skips setting formatter for handler. And this results in plaintext messages.

**Comment by galli-leo** [comment]
@sashgorokhov Sorry should have removed that, I tried that without it initially and it didn’t work as well.

**Comment by sashgorokhov** [comment]
Also `format` param should be `fmt`. Try that.

**Comment by galli-leo** [comment]
@sashgorokhov I also have tried both of these and fmt leads to no formatting at all (i.e. just the message), while format leads to the screenshot above.

**Comment by sashgorokhov** [comment]
After logging configuration, could you please run 

```python
print(my_logger.handlers[0].formatter)
```

this will show with wich formatter TelegramHandler is configured

**Comment by galli-leo** [comment]
@sashgorokhov Hmm seems like it's not using the telegram formatter at all: `<logging.Formatter object at 0x10a972190>` What do you think could be the reason for that?

**Comment by sashgorokhov** [comment]
Make sure that your recent configuration really has `fmt` instead of `format` and `parse_mode` param is skipped.

**Comment by galli-leo** [comment]
Yes made sure that I tried all combinations, none of them worked correctly.

**Comment by galli-leo** [comment]
@sashgorokhov The problem is, you are not using the result of formatException inside format of your HTMLFormatter class. You would need to either call formatException again and append that to the message, or use the already formatted record when calling super.
