### ISSUE TITLE
botapi.antrekod.ru seems to be broken

### ISSUE THREAD

**Issue by k0t3n** [sashgorokhov/python-telegram-handler#19]
To send messages, a third-party API is used (you didn’t even notify the users and did not provide the setting for using the standard telegram API, it is very unsecure) and it is unstable. Currently, messages are not sent, the service responds with error 409.
Please add customization for alternating third-party and original API.

**Comment by sashgorokhov** [comment]
What are you talking about? What is botapi.antrekod.ru?

**Comment by k0t3n** [comment]
@sashgorokhov it seems these are your changes
https://github.com/sashgorokhov/python-telegram-handler/blob/7bb5838ce0c274bc76553bbaf6937e90517c68df/telegram_handler/handlers.py#L39

**Comment by sashgorokhov** [comment]
Whoopsie

**Comment by k0t3n** [comment]
Well, any updates?

**Comment by sashgorokhov** [comment]
New release with fix of that is on pypi. Also made API endpoint configurable through handler class attribute.
